clang build: unused result value
```
second/yaboot.c:1510:13: error: variable 'result' set but not used [-Werror,-Wunused-but-set-variable]
 1510 |      int i, result;
      |             ^
```

```
second/fs_swap.c:90:15: error: unused variable 'rc' [-Werror,-Wunused-variable]
   90 |           int rc = prom_readblocks(file->of_device, blk, BLKCOUNT, buffer);
      |               ^~
```

Signed-off-by: Pepper Gray <hello@peppergray.xyz>